"""empty message

Revision ID: f75c2cbf2a8d
Revises: 
Create Date: 2022-12-07 18:45:29.260673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75c2cbf2a8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_members', sa.Column('channel_name', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'channel_members', 'channels', ['channel_name'], ['channel_name'])
    op.add_column('user_posts', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_posts', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_posts', type_='foreignkey')
    op.drop_column('user_posts', 'channel_id')
    op.drop_constraint(None, 'channel_members', type_='foreignkey')
    op.drop_column('channel_members', 'channel_name')
    # ### end Alembic commands ###
